name: "Presubmit Action"
on: [push, pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: "npm install"
      run: npm install

    - name: "npm run build"
      run: npm run-script build

    - name: "npm install mocha"
      run: npm install -g mocha

    - name: "npm test"
      run: npm test
