name: "Presubmit Action"
on: [push, pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.12.0'

    - name: "npm install"
      run: npm install
    
    - name: "npm install"
      run: npm install -g mocha
    
    - name: "npm run build"
      run: npm run-script build

    # - name: "npm test"
    #   run: npm test
