name: "Test kfctl typescript-action"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: engineerd/setup-kind@v0.1.0
        with:
            image: "kindest/node:v1.15.0@sha256:b4d092fd2b507843dd096fe6c85d06a27a0cbd740a0b32a880fe61aba24bb478"

    - name: testing KinD
      run: |
        export KUBECONFIG="$(kind get kubeconfig-path)"
        kubectl cluster-info
        kubectl get po -n kube-system
    - run: npm ci
    - run: npm run build
# TODO(swiftdiaries): Add tests back
#    - run: npm test
    - uses: ./
      with: 
        milliseconds: 1000
